export enum ClientMessageType {
  CONNECTION = 'CONNECTION',
  QUEUE = 'QUEUE',
  DEQUEUE = 'DEQUEUE',
  ACCEPT_PROPOSAL = 'ACCEPT_PROPOSAL',
  DECLINE_PROPOSAL = 'DECLINE_PROPOSAL',
  LEAVE_GAME = 'LEAVE_GAME',
  REJOIN_GAME = 'REJOIN_GAME',
  TURN_END = 'TURN_END',
  ASK_STATE = 'ASK_STATE',
  ASK_POSSIBLE_PATHS = 'ASK_POSSIBLE_PATHS',
  PATH = 'PATH',
  ACTION = 'ACTION',
}
