export enum GameEventTypeEnum {
  ADD_EFFECT_REQUEST,
  ADD_EFFECT_RESPONSE,

  REMOVE_EFFECT_REQUEST,
  REMOVE_EFFECT_RESPONSE,

  DAMAGE_REQUEST,
  DAMAGE_RESPONSE,

  HEAL_REQUEST,
  HEAL_RESPONSE,

  SHIELD_REQUEST,
  SHIELD_RESPONSE,
}
